import pandas as pd

messages = [
    # ===== MESSAGES NON TOXIQUES (40) =====
    ("Bonjour, comment ça va ?", 0),
    ("Super stream aujourd'hui !", 0),
    ("J'adore ce jeu", 0),
    ("Merci pour le contenu", 0),
    ("GG bien joué", 0),
    ("Merci beaucoup", 0),
    ("Pas mal", 0),
    ("J'ai appris beaucoup de choses, merci !", 0),
    ("Comment faire cette quête ?", 0),
    ("Merci pour le stream", 0),
    ("Excellent gameplay", 0),
    ("C'était une belle partie", 0),
    ("J'aime bien ta stratégie", 0),
    ("Continue comme ça", 0),
    ("Bonne chance pour la suite", 0),
    ("Quelle est ta config ?", 0),
    ("Tu joues depuis combien de temps ?", 0),
    ("C'est quel niveau ça ?", 0),
    ("Franchement respect", 0),
    ("Tu gères grave", 0),
    ("MDR cette action", 0),
    ("Incroyable ce clutch", 0),
    ("Premier stream que je regarde, c'est cool", 0),
    ("Tu stream tous les jours ?", 0),
    ("Salut tout le monde", 0),
    ("Hype pour ce jeu", 0),
    ("Je vais follow direct", 0),
    ("Tu mérites plus de viewers", 0),
    ("Bonne ambiance ici", 0),
    ("Quelqu'un peut expliquer ?", 0),
    ("C'est quoi le nom de cette map ?", 0),
    ("Tu recommandes ce jeu ?", 0),
    ("J'ai hâte de voir la suite", 0),
    ("Bien essayé quand même", 0),
    ("Dommage pour cette partie", 0),
    ("Tu vas y arriver", 0),
    ("Courage pour le boss", 0),
    ("Intéressant comme build", 0),
    ("Je prends des notes", 0),
    ("Merci pour les conseils", 0),
    
    # ===== MESSAGES TOXIQUES (40) =====
    ("T'es vraiment nul", 1),
    ("Va te faire voir", 1),
    ("Espèce d'idiot", 1),
    ("T'es qu'un loser", 1),
    ("Ferme ta gueule", 1),
    ("tu es nul", 1),
    ("Tu pues la merde", 1),
    ("retourne jouer à ROBLOX", 1),
    ("Trop guez", 1),
    ("T'es vraiment mauvais", 1),
    ("Arrête de jouer sérieux", 1),
    ("Désinstalle le jeu", 1),
    ("Tu sais pas jouer", 1),
    ("N'importe quoi ce gameplay", 1),
    ("T'es un bot ou quoi", 1),
    ("Pire joueur que j'ai vu", 1),
    ("Tu joues avec les pieds", 1),
    ("Retourne à l'école", 1),
    ("T'as acheté ton compte", 1),
    ("Arrête de streamer tu fais pitié", 1),
    ("Personne regarde ton stream de toute façon", 1),
    ("T'es qu'une merde", 1),
    ("Va crever", 1),
    ("Dégage de ce jeu", 1),
    ("Tu me dégoûtes", 1),
    ("T'es pathétique", 1),
    ("Sale noob", 1),
    ("Tu fais honte", 1),
    ("Ton stream est mort", 1),
    ("Zéro skill", 1),
    ("Tu te crois bon", 1),
    ("Arrête de parler tu m'énerves", 1),
    ("Personne t'aime ici", 1),
    ("T'es ridicule", 1),
    ("Quel déchet", 1),
    ("Tu perds mon temps", 1),
    ("Streameur de merde", 1),
    ("T'as aucun talent", 1),
    ("Va pleurer ailleurs", 1),
    ("T'es qu'un troll", 1),
]

# Créer le DataFrame (tableau pandas)
df = pd.DataFrame(messages, columns=['text', 'label'])

# Sauvegarder en CSV
df.to_csv(r'C:\Users\omoon\Desktop\projet ia\toxic_messages.csv', index=False)

print("Dataset créé avec succès !")

